version: 0.2

phases:
  build:
    commands:
      - mvn clean package
artifacts:
  files:
    - target/workshop-1.0.jar
    - appspec.yml
    - scripts/change_permissions.sh
    - scripts/install_dependencies.sh
    - scripts/start_server.sh
    - scripts/stop_server.sh     
  discard-paths: yes
